#!/bin/bash

PROJECT_NAME=mlops_mage \
  MAGE_CODE_PATH=/home/src \
  SMTP_EMAIL=$SMTP_EMAIL \
  SMTP_PASSWORD=$SMTP_PASSWORD \

echo "[INFO] PWD:" $PWD
echo "[INFO] PROJECT_NAME:" $PROJECT_NAME
echo "[INFO] PROJECT_NAME:" $MAGE_CODE_PATH
echo "[INFO] SMTP_EMAIL:" $SMTP_EMAIL
echo "[INFO] SMTP_PASSWORD:" $SMTP_PASSWORD
